# Configuration for CPTAC Workflow

pipeline:
  cptac:
    download_dir: "resources/data/raw/CPTAC"  # Directory for downloading CPTAC data
    processed_dir: "resources/data/processed/CPTAC"  # Directory for processed CPTAC files
    max_threads: 4  # Maximum threads for parallel processing
    metadata_file: "resources/data/metadata/cptac_metadata/cptac_summary.json"  # File for metadata storage

etl:
  temp_dir: "resources/data/temp/cptac"  # Temporary directory for intermediate files
  retries:
    max_attempts: 3  # Number of retry attempts for failed downloads
    delay: 5  # Delay (in seconds) between retries
  cleanup: true  # Clean up temp files after successful processing

results:
  proteomics: "resources/results/Proteomics"  # Directory for storing CPTAC proteomics results
  phosphoproteomics: "resources/results/Phosphoproteomics"  # Directory for phosphoproteomics results
