# General Project Configuration
project:
  name: "HNSC Omics Database"
  description: "A multi-omics database and pipeline for analyzing Head and Neck Cancer datasets."

# Spatial Transcriptomics Configuration
spatial_transcriptomics:
  raw_data_dir: "/mnt/d/HNSC_Omics_Data/raw/GEO/GSE208253"  # Raw spatial transcriptomics data
  processed_data_dir: "/mnt/d/HNSC_Omics_Data/processed/Spatial_Transcriptomics"  # Processed data directory
  results_dir: "/mnt/d/HNSC_Omics_Data/results/Spatial_Transcriptomics"  # Analysis results directory
  temp_dir: "/mnt/d/HNSC_Omics_Data/temp/spatial_transcriptomics"  # Temporary working directory

# GEO Pipeline Configuration
geo_pipeline:
  metadata_downloader:
    output_dir: "/mnt/d/HNSC_Omics_Data/metadata/geo_metadata/raw_metadata"  # Directory for raw GEO metadata
    input_file: "/mnt/c/Users/ajboo/BookAbraham/BiologicalDatabases/HNSC_Omics_Database/resources/geo_ids.txt"  # GEO IDs file
    download:
      timeout: 30  # HTTP timeout in seconds
      retries: 3  # Retry attempts for failed downloads
      retry_delay: 5  # Delay between retries in seconds

# General Logging Configuration
logging:
  log_dir: "/mnt/c/Users/ajboo/BookAbraham/BiologicalDatabases/HNSC_Omics_Database/logs"  # Directory for log files
  log_level: "INFO"  # Logging level (DEBUG, INFO, WARNING, ERROR)

# Temporary File Cleanup Settings
etl:
  cleanup: true  # Clean up temporary files after successful processing
